---
- hosts: master
  #  become: true
  user: edureka

  tasks:
    - name: check version
      command: kubectl --kubeconfig /home/edureka/.kube/admin.conf version

    - name: create deployment
      command: kubectl --kubeconfig /home/edureka/.kube/admin.conf apply -f abc-deployment.yaml

      args:
        chdir: /project/abc-technologies/kubernetes-files

    - name: create service
      command: kubectl --kubeconfig /home/edureka/.kube/admin.conf apply -f abc-service.yaml

      args:
        chdir: /project/abc-technologies/kubernetes-files

    - name: update deployment if pods updated in container repository
      command: kubectl --kubeconfig /home/edureka/.kube/admin.conf rollout restart deployment.apps/abc-deploy
