apiVersion: apps/v1
Kind: Deployment
metadata:
  name: abc-deploy
  labels:
    app: abc-app
    rsc: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-app
  template:
    metadata:
      labels:
        app: abc-app
        rsc: pod
    spec:
      containers:
      - image: vivekgupta434/abcapp-ans:latest
        name: abc-cont
