apiVersion: v1
kind: Service
metadata:
  name: abc-svc
  labels:
    app: abc-app
    rsc: service
spec:
  type: NodePort
  selector:
    app: abc-app
  ports:
  - protocol: TCP
    nodePort: 31000
    targetPort: 8080
    port: 80
